/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PublicIndexRouteImport } from './pages/_public/index'
import { Route as PublicAuthRouteImport } from './pages/_public/auth'
import { Route as PrivateDenunciaRouteImport } from './pages/_private/denuncia'

const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/_public/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateDenunciaRoute = PrivateDenunciaRouteImport.update({
  id: '/_private/denuncia',
  path: '/denuncia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/denuncia': typeof PrivateDenunciaRoute
  '/auth': typeof PublicAuthRoute
  '/': typeof PublicIndexRoute
}
export interface FileRoutesByTo {
  '/denuncia': typeof PrivateDenunciaRoute
  '/auth': typeof PublicAuthRoute
  '/': typeof PublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private/denuncia': typeof PrivateDenunciaRoute
  '/_public/auth': typeof PublicAuthRoute
  '/_public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/denuncia' | '/auth' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/denuncia' | '/auth' | '/'
  id: '__root__' | '/_private/denuncia' | '/_public/auth' | '/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateDenunciaRoute: typeof PrivateDenunciaRoute
  PublicAuthRoute: typeof PublicAuthRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/auth': {
      id: '/_public/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/denuncia': {
      id: '/_private/denuncia'
      path: '/denuncia'
      fullPath: '/denuncia'
      preLoaderRoute: typeof PrivateDenunciaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PrivateDenunciaRoute: PrivateDenunciaRoute,
  PublicAuthRoute: PublicAuthRoute,
  PublicIndexRoute: PublicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
