/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PublicIndexRouteImport } from './pages/_public/index'
import { Route as PublicDenunciasRouteImport } from './pages/_public/denuncias'
import { Route as PublicContatosRouteImport } from './pages/_public/contatos'
import { Route as PrivateReportarRouteImport } from './pages/_private/reportar'
import { Route as PublicAutenticacaoIndexRouteImport } from './pages/_public/autenticacao/index'

const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDenunciasRoute = PublicDenunciasRouteImport.update({
  id: '/_public/denuncias',
  path: '/denuncias',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicContatosRoute = PublicContatosRouteImport.update({
  id: '/_public/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateReportarRoute = PrivateReportarRouteImport.update({
  id: '/_private/reportar',
  path: '/reportar',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAutenticacaoIndexRoute = PublicAutenticacaoIndexRouteImport.update({
  id: '/_public/autenticacao/',
  path: '/autenticacao/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/reportar': typeof PrivateReportarRoute
  '/contatos': typeof PublicContatosRoute
  '/denuncias': typeof PublicDenunciasRoute
  '/': typeof PublicIndexRoute
  '/autenticacao': typeof PublicAutenticacaoIndexRoute
}
export interface FileRoutesByTo {
  '/reportar': typeof PrivateReportarRoute
  '/contatos': typeof PublicContatosRoute
  '/denuncias': typeof PublicDenunciasRoute
  '/': typeof PublicIndexRoute
  '/autenticacao': typeof PublicAutenticacaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private/reportar': typeof PrivateReportarRoute
  '/_public/contatos': typeof PublicContatosRoute
  '/_public/denuncias': typeof PublicDenunciasRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/autenticacao/': typeof PublicAutenticacaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/reportar' | '/contatos' | '/denuncias' | '/' | '/autenticacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/reportar' | '/contatos' | '/denuncias' | '/' | '/autenticacao'
  id:
    | '__root__'
    | '/_private/reportar'
    | '/_public/contatos'
    | '/_public/denuncias'
    | '/_public/'
    | '/_public/autenticacao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateReportarRoute: typeof PrivateReportarRoute
  PublicContatosRoute: typeof PublicContatosRoute
  PublicDenunciasRoute: typeof PublicDenunciasRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAutenticacaoIndexRoute: typeof PublicAutenticacaoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/denuncias': {
      id: '/_public/denuncias'
      path: '/denuncias'
      fullPath: '/denuncias'
      preLoaderRoute: typeof PublicDenunciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/contatos': {
      id: '/_public/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof PublicContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/reportar': {
      id: '/_private/reportar'
      path: '/reportar'
      fullPath: '/reportar'
      preLoaderRoute: typeof PrivateReportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/autenticacao/': {
      id: '/_public/autenticacao/'
      path: '/autenticacao'
      fullPath: '/autenticacao'
      preLoaderRoute: typeof PublicAutenticacaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PrivateReportarRoute: PrivateReportarRoute,
  PublicContatosRoute: PublicContatosRoute,
  PublicDenunciasRoute: PublicDenunciasRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicAutenticacaoIndexRoute: PublicAutenticacaoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
